### ISSUE TITLE
Flake8 not breaking build

### ISSUE THREAD

**Issue by lucasmoura** [aimacode/aima-python#304] opened 2017-03-03 13:06 UTC
I have noticed in the .travis.yml file that the flake8 command does not break the build if it returns some warnings. Does that command breaks the build if only some flake8 warnings are triggered or should it not break the build at all ?

**Comment by Chipe1** [comment] 2017-03-28 11:13
@norvig Your opinion on this?
I personally think we should not impose any automated style checks. Even if we do so, styling is a subjective matter and we must first decide which rules are important enough to break the build and which rules can be relaxed.

**Comment by lucasmoura** [comment] 2017-03-28 13:04
@Chipe1 Yes, we should definitely look if that are more warnings that should be ignored by the project. Currently, we are ignoring the same rules as the ones ignored by running flake8 after a travis.yml successful build.

However, flake8 is not only used to perform style check. It is a static analysis tool as well, which can be really usefull to capture some bugs in the code. Issues such as #398 could be avoided with we allow that kind of analysis.

But again, I do agree that we should discuss what should be ignored or relaxed in order for the tool to better serve the project's needs. Also @norvig of that issue would also clarify better what these needs are.

**Comment by sofmonk** [comment] 2017-03-28 13:14
At the end, we need good documented code and that will come from imposing such checks, but what the problem is that some merged file 'A' breaks the checks because of which the updated new file B is not able to pass the build.

**Closed** 2017-06-18 13:41 UTC
