### ISSUE TITLE
Build Broken

### ISSUE THREAD

**Issue by norvig** [aimacode/aima-python#289] opened 2017-03-01 03:45 UTC
Somewhere along the way the build got broken. Would like to see it fixed again!

**Comment by kshitij10496** [comment] 2017-03-01 09:45
The commit 9f7f4df started breaking the build.
Also, we need to check whether the commits merged after 9f7f4df (namely, 0e46096 and 123571e) are building properly.
I will try to fix it up.

**Comment by reachtarunhere** [comment] 2017-03-01 09:51
The issue was due to Travis + Setuptools and not due to our code. The build works now. [Another Project - Same Issue](https://github.com/pypa/setuptools/issues/942)

I just had to press rebuild on Travis to get this working. No change in config was required.

**Comment by MrDupin** [comment] 2017-03-01 16:43
It seems that the issue is still not fixed, I'm afraid. I made a trivial pull request (fixing typos in comments) but Travis could not built.

**Comment by reachtarunhere** [comment] 2017-03-01 18:06
@MrDupin Yeah the build still fails occasionally. I am trying to look into it. I feel adding six to the travis config file should work.

**Comment by reachtarunhere** [comment] 2017-03-02 11:25
This issue has been fixed but I can't find a way to restart builds for old PRs with new config file. Anyone has any idea how to go about this?

**Comment by MrDupin** [comment] 2017-03-02 16:30
If new PRs work, we could make new PRs for the old ones (at least, the ones that we want to commit). I checked a few of them and it wouldn't be too much work.

Some of them have built already, like #292 and #294.

**Comment by reachtarunhere** [comment] 2017-03-02 17:46
It will work for PRs with recent commits and it might or might not for the older PRs. I guess we can safely close this now.

**Closed by reachtarunhere** 2017-03-02 17:46 UTC
Labels: help wanted
